export const USER_LOGIN = "USER_LOGIN";
export const USER_UPDATE = "USER_UPDATE";
export const USER_REGISTER = "USER_REGISTER";

export const LOADING = "LOADING";

export const ADD_ANIMAL = "ADD_ANIMAL";
export const GET_ALL_ANIMAL = "GET_ALL_ANIMAL";
export const UPDATE_ANIMAL = "UPDATE_ANIMAL";
export const DELETE_ANIMAL = "DELETE_ANIMAL";
export const GET_ANIMAL_DETAIL = "GET_ANIMAL_DETAIL";
export const GET_USER_ANIMAL = "GET_USER_ANIMAL";
export const DELETE_USER_ANIMAL = "DELETE_USER_ANIMAL";
export const UPDATE_USER_ANIMAL = "UPDATE_USER_ANIMAL";

export const ADD_INJURED_ANIMAL = "ADD_INJURED_ANIMAL";
export const GET_ALL_INJURED_ANIMAL = "GET_ALL_INJURED_ANIMAL";
export const UPDATE_INJURED_ANIMAL = "UPDATE_INJURED_ANIMAL";
export const DELETE_INJURED_ANIMAL = "DELETE_INJURED_ANIMAL";
export const GET_INJURED_ANIMAL_DETAIL = "GET_INJURED_ANIMAL_DETAIL";
export const GET_USER_INJURED_ANIMAL = "GET_USER_INJURED_ANIMAL";
export const DELETE_USER_INJURED_ANIMAL = "DELETE_USER_INJURED_ANIMAL";
export const UPDATE_USER_INJURED_ANIMAL = "UPDATE_USER_INJURED_ANIMAL";